{% set name = "mkdocstrings-python-legacy" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-python-legacy-{{ version }}.tar.gz
  sha256: f0e7ec6a19750581b752acb38f6b32fcd1efe006f14f6703125d2c2c9a5c6f02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - pdm
  run:
    - mkdocstrings >=0.18
    - python >=3.7
    - pytkdocs >=0.14

test:
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest >=6.2
    - pytest-xdist >=2.4
    - pytest-randomly>=3.10
  files:
    - tests.py
  source_files:
    - tests

about:
  home: https://pypi.org/project/mkdocstrings-python-legacy/
  summary: A legacy Python handler for mkdocstrings.
  license: MIT
  license_file: LICENSE
  doc_url: https://mkdocstrings.github.io/python-legacy
  dev_url: https://github.com/mkdocstrings/python-legacy

extra:
  recipe-maintainers:
    - bandersen23
