{% set name = "mkdocstrings-python-legacy" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-python-legacy-{{ version }}.tar.gz
  sha256: 3fb58fdabe19c6b52b8bb1d3bb1540b1cd527b562865468d6754e8cd1201050c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7
    - pdm
  run:
    - mkdocstrings >=0.19
    - python >=3.7
    - pytkdocs >=0.14

test:
  imports:
    - mkdocstrings_handlers.python
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mkdocstrings-python-legacy/
  summary: A legacy Python handler for mkdocstrings.
  license: MIT
  license_file: LICENSE
  doc_url: https://mkdocstrings.github.io/python-legacy
  dev_url: https://github.com/mkdocstrings/python-legacy

extra:
  recipe-maintainers:
    - bandersen23
